name: Despliegue en producción

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar el entorno de Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Leer versión desde Cargo.toml
        id: get_version
        run: echo "::set-output name=version::$(awk -F\" '/^version/ {print $2}' jast_lib/Cargo.toml)"

      - name: Build
        run: cargo build --release --manifest-path jast_lib/Cargo.toml

      - name: Iniciar sesión en crates.io
        run: cargo login --registry crates.io ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publicar
        run: cargo publish --manifest-path jast_lib/Cargo.toml
