name: version deploy

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rust environment settings
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo.toml version
        id: get_version
        run: echo "::set-output name=version::$(awk -F\" '/^version/ {print $2}' jast_lib/Cargo.toml)"

      - name: Build
        run: cargo build --release --manifest-path jast_lib/Cargo.toml

      - name: Publish on crates.io
        run: cargo publish --manifest-path jast_lib/Cargo.toml
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

